resources:
- name: repo
  type: git
  source:
    uri: https://github.com/chad2448/test-repo.git
    branch: main

  
jobs:
- name: pipe-test
  plan:
  - get: repo
    trigger: true
  - task: build-and-test
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: 
          #repository: busybox
          repository: golang
          tag: 1.22.1-alpine3.19
      inputs:
      - name: repo
      #outputs:
      #- name: repo
      run:
        path: sh 
        args:
        - -cx
        - |
          cd repo
          sh test-2.sh
